services:
  mongodb:
    image: mongo:8
    container_name: catneural-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - catneural_data:/data/db

volumes:
  catneural_data:
